[project]
name = "shift-scheduling-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pulp>=3.2.2",
    "ruff>=0.12.9",
    "streamlit>=1.48.1",
]
